Updated links to JT-VAE repo as it was renamed
uiocompcat/tmcinvdes pull request #42
Opened 2024-09-13 07:05 UTC by Strandgaard96

2024-09-13 10:33 UTC, tlinjordet commented
Thanks for the PR, this is a good size for something without a predefined issue.

I like the new JT-VAE-tmcinvdes repo name!

However, I cannot see the point in adding double backslashes to the math notation, at least in VScode markdown preview it breaks the math rendering. 

Here in GitHub it looks like both versions render as intended:

Current version: `$\mathbf{(1 \rightarrow 2)}$` which renders as $\mathbf{(1 \rightarrow 2)}$; versus
This PR: `$\\mathbf{(1 \\rightarrow 2)}$` which renders as $\\mathbf{(1 \\rightarrow 2)}$.

2024-09-13 11:01 UTC, Strandgaard96 commented
Somehow the auto-formatting in my markdown editor added the extra backslash. 
Agree, should not be there, is removed now :)

2024-09-18 10:02 UTC, tlinjordet requested changes
I had requested a few minor changes in the comments in addition to the double backslash. This may have been missed, hence changing review status to request changes.

2024-09-18 10:02 UTC, tlinjordet commented on DETAILS.md
> +- $\\mathbf{(1 \\rightarrow 2)}$: Train unconditional JT-VAE models. This is done with code in the separate JT-VAE repository [https://github.com/Strandgaard96/JT-VAE-tmcinvdes/](https://github.com/S
We can probably change this instance on this line to `[JT-VAE-tmcinvdes](https://github.com/Strandgaard96/JT-VAE-tmcinvdes/)` as well, i.e., no need to show the entire URL.

We can also use `[JT-VAE-tmcinvdes](https://github.com/Strandgaard96/JT-VAE-tmcinvdes/)` everywhere and not just `[JT-VAE](https://github.com/Strandgaard96/JT-VAE-tmcinvdes/)`.

2024-09-18 10:02 UTC, tlinjordet commented on DETAILS.md
> +  - `tmcinvdes/quantum_chemistry/orca/parse_orca_to_labels.py` *(Re-used from $\\mathbf{(6 \\rightarrow 7)}$.)*
I see now that the italics break the math rendering on the GitHub website. Could you change this line to:
```
  - `tmcinvdes/quantum_chemistry/orca/parse_orca_to_labels.py` *(Re-used from * $\mathbf{(6 \rightarrow 7)}$ *.)*
```
rendering as: 
  - `tmcinvdes/quantum_chemistry/orca/parse_orca_to_labels.py` *(Re-used from* $\mathbf{(6 \rightarrow 7)}$*.)*

2024-09-18 12:16 UTC, Strandgaard96 commented
Thanks for checking, the links are updated now, as well as the suggested line : )

2024-09-18 13:13 UTC, tlinjordet approved these changes

2024-09-18 13:14 UTC, merged